In [2]:
import numpy as np
import pandas as pd

In [3]:
#creat a banking_data: 10 rows x 5 columns
#banking_data columns: Customer_Id,Account_balance,Credit_Score,Transaction_Count,Year_Active.
banking_data=np.array([
   [1001, 18450.75, 720, 25, 5],
    [1002, 9750.50, 640, 12, 2],
    [1003, 32400.30, 810, 41, 9],
    [1004, 2150.90, 590, 7, 1],
    [1005, 14230.65, 705, 30, 6],
    [1006, 6870.40, 670, 19, 3],
    [1007, 40120.80, 845, 52, 11],
    [1008, 3980.25, 610, 14, 2],
    [1009, 22450.55, 735, 33, 7],
    [1010, 11670.10, 690, 21, 4]
])


In [4]:
import numpy as pd
np.set_printoptions(suppress=True,precision=2)
print(banking_data)
print(f"\nBanking data shape:{banking_data.shape}")

print(f"\nBaking data type:{banking_data.dtype}")

[[ 1001.   18450.75   720.      25.       5.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1004.    2150.9    590.       7.       1.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1006.    6870.4    670.      19.       3.  ]
 [ 1007.   40120.8    845.      52.      11.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1010.   11670.1    690.      21.       4.  ]]

Banking data shape:(10, 5)

Baking data type:float64


#Question 1: Array Creation and Manipulation

In [5]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Q1.2: Create an array of 8 zeros using np.zeros()
array_zeros=np.zeros(8)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Q1.3: Create an array of 6 ones using np.ones()
array_ones=np.ones(6)
print(array_ones)

[1. 1. 1. 1. 1. 1.]


In [31]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
arrays_range=np.arange(0,15)
print(arrays_range)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
array_line=np.linspace(0,100,8)
print(array_line)

[  0.    14.29  28.57  42.86  57.14  71.43  85.71 100.  ]


#Question 2: Array Attributes and Information

In [36]:
# Q2.1: What is the shape of the banking_data array?
shape=np.shape(banking_data)
print(f"Shape of Banking data: {shape}")
           #Or#
print(f"Shape of Banking data: {banking_data.shape}")           


Shape of Banking data: (10, 5)
Shape of Banking data: (10, 5)


In [37]:
# Q2.2: What is the data type of the banking_data array?
print(f"data type:{banking_data.dtype}")

data type:float64


In [38]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
print(f"the Sixe of Banking Data:{banking_data.size}")

the Sixe of Banking Data:50


In [40]:
# Q2.4: What is the number of dimensions of the banking_data array?
num_dimension=np.ndim(banking_data)
print(f"Dimension:{num_dimension}")

Dimension:2


In [41]:
# Q2.5: What is the memory size of the banking_data array in bytes?
print(f"The memory size is:{banking_data.nbytes}")

The memory size is:400


#Question 3: Indexing and Slicing

In [46]:
# Q3.1: Extract the first row of banking_data
first_row=banking_data[0]
print(first_row)

[ 1001.   18450.75   720.      25.       5.  ]


In [47]:
# Q3.2: Extract the last row of banking_data
last_row=banking_data[-1]
print(f"last row:{last_row}")

last row:[ 1010.  11670.1   690.     21.      4. ]


In [48]:
# Q3.3: Extract the Account_Balance column (column index 1)
account_col=banking_data[:,1]
print(f"Account balance column:{account_col}")


Account balance column:[18450.75  9750.5  32400.3   2150.9  14230.65  6870.4  40120.8   3980.25
 22450.55 11670.1 ]


In [53]:
# Q3.4: Extract the first 4 rows and first 3 columns
rows_ccolumns=banking_data[:4,:3]
print(f"First 4 rows and 3 Columns:{rows_ccolumns}")

First 4 rows and 3 Columns:[[ 1001.   18450.75   720.  ]
 [ 1002.    9750.5    640.  ]
 [ 1003.   32400.3    810.  ]
 [ 1004.    2150.9    590.  ]]


In [55]:
# Q3.5: Extract rows 3 to 7 (inclusive)
rows_7to8=banking_data[2:7,:]
print(rows_7to8)

[[ 1003.   32400.3    810.      41.       9.  ]
 [ 1004.    2150.9    590.       7.       1.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1006.    6870.4    670.      19.       3.  ]
 [ 1007.   40120.8    845.      52.      11.  ]]


#Question 4: Mathematical Operations

In [56]:
# Q4.1: Calculate the sum of all account balances
sum_account=np.sum(banking_data[:,1])
print(f"Sum of Account balance:{sum_account}")

Sum of Account balance:162075.2


In [57]:
# Q4.2: Calculate the mean account balance
mean_account=np.mean(banking_data[:,1])
print(f"Mean of Account balance:{mean_account}")

Mean of Account balance:16207.52


In [58]:
# Q4.3: Calculate the standard deviation of account balances
standard=np.std(banking_data[:,1])
print(f"Standard devaition of account balance:\n{standard}")

Standard devaition of account balance:
11741.057868888987


In [59]:
# Q4.4: Calculate the variance of account balances
variance=np.var(banking_data[:,1])
print(f"Variance of account balance:{variance}")

Variance of account balance:137852439.8806


In [60]:
# Q4.5: Calculate the median account balance
median=np.median(banking_data[:,1])
print(f"Median of Account baalnce :{median}")

Median of Account baalnce :12950.375



3Question 5: Statistical Functions


In [5]:
# Q5.1: Find the minimum and maximum account balances
min_balance=np.min(banking_data[:,1])
max_balance=np.max(banking_data[:,1])
print(f"minimum balance:{min_balance}")
print(f"maximum balance:{max_balance}")

minimum balance:2150.9
maximum balance:40120.8


In [6]:
# Q5.2: Find the minimum and maximum credit scores
min_credit=np.min(banking_data[:,2])
max_credit=np.max(banking_data[:,2])
print(f"Minimum credit score:{min_credit}")
print(f"Maximum credit score:{max_credit}")

Minimum credit score:590.0
Maximum credit score:845.0


In [8]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentile=np.percentile(banking_data[:,1],[25,50,70])
print(f"25th percentile of balance: {percentile[0]}")
print(f"50th percentile of balance: {percentile[1]}")
print(f"75th percentile of balance: {percentile[2]}")

25th percentile of balance: 7590.424999999999
50th percentile of balance: 12950.375
75th percentile of balance: 19650.69


In [11]:
# Q5.4: Calculate the correlation between account balance and credit score
correlation=np.corrcoef((banking_data[:,1]),(banking_data[:,2]))[0,1]
print(f"Correlation of Account Balancea and Credit Score:{correlation:.4f}")

Correlation of Account Balancea and Credit Score:0.9780


In [12]:
# Q5.5: Calculate the covariance between account balance and credit score
covariance=np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(f"Covariance of Acount Balance and Credit Score:{covariance:.4f}")

Covariance of Acount Balance and Credit Score:984634.3556


#Question 6: Array Reshaping and Manipulation

In [15]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped_data=banking_data.reshape(5,10)
print(reshaped_data)

[[ 1001.   18450.75   720.      25.       5.    1002.    9750.5    640.
     12.       2.  ]
 [ 1003.   32400.3    810.      41.       9.    1004.    2150.9    590.
      7.       1.  ]
 [ 1005.   14230.65   705.      30.       6.    1006.    6870.4    670.
     19.       3.  ]
 [ 1007.   40120.8    845.      52.      11.    1008.    3980.25   610.
     14.       2.  ]
 [ 1009.   22450.55   735.      33.       7.    1010.   11670.1    690.
     21.       4.  ]]


In [16]:
# Q6.2: Flatten the banking_data to a 1D array
flatted_data=banking_data.flatten()
print(flatted_data)

[ 1001.   18450.75   720.      25.       5.    1002.    9750.5    640.
    12.       2.    1003.   32400.3    810.      41.       9.    1004.
  2150.9    590.       7.       1.    1005.   14230.65   705.      30.
     6.    1006.    6870.4    670.      19.       3.    1007.   40120.8
   845.      52.      11.    1008.    3980.25   610.      14.       2.
  1009.   22450.55   735.      33.       7.    1010.   11670.1    690.
    21.       4.  ]


In [17]:
# Q6.3: Transpose the banking_data
transpose=banking_data.T
print(transpose)

[[ 1001.    1002.    1003.    1004.    1005.    1006.    1007.    1008.
   1009.    1010.  ]
 [18450.75  9750.5  32400.3   2150.9  14230.65  6870.4  40120.8   3980.25
  22450.55 11670.1 ]
 [  720.     640.     810.     590.     705.     670.     845.     610.
    735.     690.  ]
 [   25.      12.      41.       7.      30.      19.      52.      14.
     33.      21.  ]
 [    5.       2.       9.       1.       6.       3.      11.       2.
      7.       4.  ]]


In [21]:
# Q6.4: Split the banking_data into 2 equal parts vertically
split_data=np.vsplit(banking_data,2)
print(f"1st Split:\n{split_data[0]}")
print(f"2st Split:\n{split_data[1]}")


1st Split:
[[ 1001.   18450.75   720.      25.       5.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1004.    2150.9    590.       7.       1.  ]
 [ 1005.   14230.65   705.      30.       6.  ]]
2st Split:
[[ 1006.    6870.4    670.      19.       3.  ]
 [ 1007.   40120.8    845.      52.      11.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1010.   11670.1    690.      21.       4.  ]]


In [24]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
horizontal_split=np.array_split(banking_data,2,)
print(f"1st Split:\n{horizontal_split[0]}")
print(f"2st Split:\n{horizontal_split[1]}")


1st Split:
[[ 1001.   18450.75   720.      25.       5.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1004.    2150.9    590.       7.       1.  ]
 [ 1005.   14230.65   705.      30.       6.  ]]
2st Split:
[[ 1006.    6870.4    670.      19.       3.  ]
 [ 1007.   40120.8    845.      52.      11.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1010.   11670.1    690.      21.       4.  ]]


#Question 7: Logical Operations and Filtering

In [27]:
# Q7.1: Find customers with account balance greater than $100,000
greatest_balance=banking_data[banking_data[:,1]<10000]
print(f"Accounted Holders:\n{greatest_balance}")

Accounted Holders:
[[1002.   9750.5   640.     12.      2.  ]
 [1004.   2150.9   590.      7.      1.  ]
 [1006.   6870.4   670.     19.      3.  ]
 [1008.   3980.25  610.     14.      2.  ]]


In [34]:
# Q7.2: Find customers with credit score greater than 800
greatest_credit=banking_data[banking_data[:,2]>800]
print(greatest_credit)

[[ 1003.  32400.3   810.     41.      9. ]
 [ 1007.  40120.8   845.     52.     11. ]]


In [36]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
transaction_count=banking_data[(banking_data[:,3]>20)&(banking_data[:,2]>700)]
print(transaction_count)
                               

[[ 1001.   18450.75   720.      25.       5.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1007.   40120.8    845.      52.      11.  ]
 [ 1009.   22450.55   735.      33.       7.  ]]


In [38]:
# print("\nQ7.4: Count how many customers have account balance between $10,000 and $100,000")
count=np.sum((banking_data[:,1]>=10000)&(banking_data[:,1]<=100000))
print(f"count of customers having account balance between $10,000 and $100,000 is : {count}")

count of customers having account balance between $10,000 and $100,000 is : 6


In [40]:
# print("\nQ7.5: Find the index of the customer with the highest credit score")
cust_highscore=np.argmax(banking_data[:2])
print(f"customer with the highest credit score : {banking_data[cust_highscore,0]}")

customer with the highest credit score : 1002.0


#Question 8: Sorting and Searching

In [ ]:
# Q8.1: Sort the banking_data by account balance (ascending)
sorted_balance=banking_data[banking_data[:,1].argsort()]
print(sorted_balance)


[[ 1004.    2150.9    590.       7.       1.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1006.    6870.4    670.      19.       3.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1010.   11670.1    690.      21.       4.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1001.   18450.75   720.      25.       5.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1007.   40120.8    845.      52.      11.  ]]


In [42]:
# Q8.2: Sort the banking_data by credit score (descending)
sorted_credit=banking_data[(-banking_data[:,1]).argsort()]
print(sorted_credit)

[[ 1007.   40120.8    845.      52.      11.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1001.   18450.75   720.      25.       5.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1010.   11670.1    690.      21.       4.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1006.    6870.4    670.      19.       3.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1004.    2150.9    590.       7.       1.  ]]


In [43]:
# Q8.3: Find the indices that would sort the array by years active
indices=np.argsort(banking_data[:,4])
print(indices)

[3 1 7 5 9 0 4 8 2 6]


In [50]:
# Q8.4: Find the customer with the second highest account balance
balance_2highest_indx=np.argsort(banking_data[:,1])[-2]
balance_2highest=banking_data[balance_2highest_indx]
print(f"Customer id:{balance_2highest[0]}, Account balance:{balance_2highest[1]}")

Customer id:1003.0, Account balance:32400.3


In [60]:
# Q8.5: Find the customer with the lowest transaction count
transaction_lowest_indx=np.argsort(banking_data[:,3])
transaction_lowest=banking_data[transaction_lowest_indx]
print(f"Customer id:{transaction_lowest[0]}, Account balance:{transaction_lowest[1]}")

Customer id:[1004.  2150.9  590.     7.     1. ], Account balance:[1002.  9750.5  640.    12.     2. ]


#Question 9: Mathematical Functions

In [52]:
# Q9.1: Calculate the absolute values of all elements
absolute_value=np.abs(banking_data)
print(absolute_value)

[[ 1001.   18450.75   720.      25.       5.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1004.    2150.9    590.       7.       1.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1006.    6870.4    670.      19.       3.  ]
 [ 1007.   40120.8    845.      52.      11.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1010.   11670.1    690.      21.       4.  ]]


In [53]:
# Q9.2: Calculate the square root of all account balances.
square_balance=np.sqrt(banking_data[:,1])
print(square_balance)

[135.83  98.74 180.    46.38 119.29  82.89 200.3   63.09 149.84 108.03]


In [54]:
# Q9.3: Calculate the square of all credit scores
square_credit=np.sqrt(banking_data[:,2])
print(square_credit)

[26.83 25.3  28.46 24.29 26.55 25.88 29.07 24.7  27.11 26.27]


In [55]:
# Q9.4: Calculate the exponential of all transaction counts
exponenetial_trans=np.exp(banking_data[:,3])
print(exponenetial_trans)

[7.20e+10 1.63e+05 6.40e+17 1.10e+03 1.07e+13 1.78e+08 3.83e+22 1.20e+06
 2.15e+14 1.32e+09]


In [56]:
# Q9.5: Calculate the natural logarithm of all account balances
logarithm=np.log(banking_data[:,1])
print(logarithm)

[ 9.82  9.19 10.39  7.67  9.56  8.83 10.6   8.29 10.02  9.36]


#Question 10: Advanced Operations

In [57]:
# Q10.1: Calculate the cumulative sum of account balances
cumulative_sum=np.cumsum(banking_data[:,1])
print(cumulative_sum)

[ 18450.75  28201.25  60601.55  62752.45  76983.1   83853.5  123974.3
 127954.55 150405.1  162075.2 ]


In [61]:
# Q10.2: Calculate the cumulative product of transaction counts
cumulative_product=np.cumprod(banking_data[:,3])
print(cumulative_product)

[2.50e+01 3.00e+02 1.23e+04 8.61e+04 2.58e+06 4.91e+07 2.55e+09 3.57e+10
 1.18e+12 2.48e+13]


In [62]:
# Q10.3: Calculate the difference between consecutive account balances
difference=np.diff(banking_data[:,1])
print(difference)

[ -8700.25  22649.8  -30249.4   12079.75  -7360.25  33250.4  -36140.55
  18470.3  -10780.45]


In [63]:
# Q10.4: Calculate the gradient of account balances
gradient=np.gradient(banking_data[:,1])
print(gradient)

[ -8700.25   6974.77  -3799.8   -9084.83   2359.75  12945.08  -1445.07
  -8835.13   3844.93 -10780.45]


In [64]:
# Q10.5: Calculate the histogram of account balances with 5 bins
histogram,binss=np.histogram(banking_data[:,1],bins=5)
print(histogram)
print(binss)

[3 3 2 1 1]
[ 2150.9   9744.88 17338.86 24932.84 32526.82 40120.8 ]


#Question 11: Random Numbers and Simulation

In [65]:
# Q11.1: Generate 6 random integers between 1 and 1000
random_int=np.random.randint(1,1000,6)
print(random_int)

[122 816 921 544 869 322]


In [69]:
# Q11.2: Generate 6 random floats between 0 and 1
random_floats=np.random.random(6)
print(random_floats)


[0.52 0.68 0.37 0.91 0.   0.91]


In [72]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
mean_num=np.random.normal(700,100,6)
print(mean_num)

[733.46 772.93 837.2  779.47 708.79 766.39]


In [82]:
# Q11.4: Shuffle the banking_data rows randomly
shuffled_data=banking_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

[[ 1007.   40120.8    845.      52.      11.  ]
 [ 1009.   22450.55   735.      33.       7.  ]
 [ 1002.    9750.5    640.      12.       2.  ]
 [ 1001.   18450.75   720.      25.       5.  ]
 [ 1010.   11670.1    690.      21.       4.  ]
 [ 1004.    2150.9    590.       7.       1.  ]
 [ 1006.    6870.4    670.      19.       3.  ]
 [ 1008.    3980.25   610.      14.       2.  ]
 [ 1003.   32400.3    810.      41.       9.  ]
 [ 1005.   14230.65   705.      30.       6.  ]]


In [84]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
random_num=np.random.random(4)
print(random_num)


[0.7  0.29 0.23 0.55]


#Question 12: Linear Algebra Operations

In [86]:
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product=np.dot((banking_data[:,1]),(banking_data[:,2]))
print(dot_product)

122557462.0


In [93]:
# Q12.2: Calculate the cross product of first two rows
cross_product=np.cross((banking_data[0,:3]),(banking_data[1,:3]))
print(cross_product)

[ 4788120.    80800. -8727401.]


In [94]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
magnitude_balance=np.linalg.norm(banking_data[:,1])
print(magnitude_balance)

63287.92494868196


In [98]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3=np.array([[2,3],[3,4]])
determinent=np.linalg.det(matrix_3x3)
print(f"array of 3x3 matrix:\n{array_3x3}")
print(f"Determinent of mtrix:{determinent}")

array of 3x3 matrix:
[[2 3]
 [3 4]]
Determinent of mtrix:-1.0000000000000004


In [102]:
# Q12.5: Calculate the inverse of the 3x3 matrix
matrix_inverse=np.linalg.inv(matrix_3x3)
print(f"Inverse of the matrix:\n{matrix_inverse}")

Inverse of the matrix:
[[-4.  3.]
 [ 3. -2.]]


#Question 13: String Operations

In [6]:
# Q13.1: Convert all customer IDs to strings
to_strings=banking_data[:,0].astype(str)
print(to_strings)


['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [106]:
# Q13.2: Check if any customer ID contains '100'
contains_100 = np.char.find(to_strings, '100') >= 0
print(contains_100)

[ True  True  True  True  True  True  True  True  True False]


In [7]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
customer_ids_uppercase=np.char.upper(to_strings)
print(customer_ids_uppercase)

['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']


In [8]:
# Q13.4: Count the length of each customer ID string
customer_ids_len=np.char.str_len(to_strings)
print(customer_ids_len)

[6 6 6 6 6 6 6 6 6 6]


In [9]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
replace=np.char.replace(to_strings,'100','CUST')
print(replace)

['CUST1.0' 'CUST2.0' 'CUST3.0' 'CUST4.0' 'CUST5.0' 'CUST6.0' 'CUST7.0'
 'CUST8.0' 'CUST9.0' '1010.0']



#Question 14: Date and Time Operations

In [11]:
# Q14.1: Convert years active to months
years_to_months=banking_data[:,4]*24
print(years_to_months)

[120.  48. 216.  24. 144.  72. 264.  48. 168.  96.]


In [14]:
# Q14.2: Calculate the average years active
avg_years=np.mean(banking_data[:,4])
print(f"The average years active :{avg_years}")

The average years active :5.0


In [16]:
# Q14.3: Find customers who have been active for more than 5 year
long_years_active=banking_data[banking_data[:,4]>5]
print(long_years_active)

[[ 1003.   32400.3    810.      41.       9.  ]
 [ 1005.   14230.65   705.      30.       6.  ]
 [ 1007.   40120.8    845.      52.      11.  ]
 [ 1009.   22450.55   735.      33.       7.  ]]


In [19]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_years=np.sum(banking_data[:,4])
print(f"The total number of years {total_years} active.")

The total number of years 50.0 active.


In [22]:
# Q14.5: Find the customer with the shortest time active
shortest_active_indx=np.argmin(banking_data[:,4])
shortest_active=banking_data[shortest_active_indx]
print(f"Customer Id:{shortest_active[0]}, acctive time: {shortest_active[4]}")

Customer Id:1004.0, acctive time: 1.0


#Question 15: Advanced Array Operations

In [14]:
# Q15.1: Apply a function to calculate 5% interest on all account balances
def add_interest(balance):
    return balance*0.5
np.vectorize(add_interest)(banking_data[:,1])
    

array([ 9225.38,  4875.25, 16200.15,  1075.45,  7115.32,  3435.2 ,
       20060.4 ,  1990.12, 11225.27,  5835.05])

In [19]:
# Q15.2: Use np.where to categorize customers by balance ranges
balance_range=np.where(banking_data[:,1]<10000,"Low Balance",
                       np.where((banking_data[:,1]>10000)&(banking_data[:,1]<20000),
                                "Medium Balance","High balance"))

print(balance_range)

['Medium Balance' 'Low Balance' 'High balance' 'Low Balance'
 'Medium Balance' 'Low Balance' 'High balance' 'Low Balance'
 'High balance' 'Medium Balance']


In [28]:
# Q15.3: Use np.select to categorize customers by credit score ranges
conditions=[
    banking_data[:,2]<600,
    (banking_data[:,2]>=640)&(banking_data[:,2]<=750),
    banking_data[:,2]>750
]
choices=["poor credit","Average credit","Excellent credit"]
categories=np.select(conditions,choices,default="Unkown")
print(categories)
print(banking_data[:,2])

['Average credit' 'Average credit' 'Excellent credit' 'poor credit'
 'Average credit' 'Average credit' 'Excellent credit' 'Unkown'
 'Average credit' 'Average credit']
[720. 640. 810. 590. 705. 670. 845. 610. 735. 690.]


In [ ]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_intrest(x):
    return x*0.03
def mid_intrest(x):
    return x*0.05
def high_intrest(x):
    return x*0.07

np.piecewise(
    banking_data[:,1],
    [banking_data[:,1]<10000,(banking_data[:,1]>10000) & (banking_data[:,1]<50000),
     banking_data[:,1]>=50000],
    [low_intrest,mid_intrest,high_intrest]
)

array([ 922.54,  292.51, 1620.02,   64.53,  711.53,  206.11, 2006.04,
        119.41, 1122.53,  583.5 ])

In [30]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
np.apply_along_axis(np.sum,1,banking_data)

array([20201.75, 11406.5 , 34263.3 ,  3752.9 , 15976.65,  8568.4 ,
       42035.8 ,  5614.25, 24234.55, 13395.1 ])

Question 16: Array Concatenation and Stacking


In [32]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
np.hstack([arr1,arr2])

array([1, 2, 3, 3, 4, 5])

In [33]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [3, 4, 5]])

In [34]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
np.concatenate([arr1,arr2])

array([1, 2, 3, 3, 4, 5])

In [35]:
# Q16.4: Stack arrays depth-wise using np.dstack()
np.dstack([arr1,arr2])

array([[[1, 3],
        [2, 4],
        [3, 5]]])

In [36]:
# Q16.5: Create a column stack using np.column_stack()
np.column_stack([arr1,arr2])

array([[1, 3],
       [2, 4],
       [3, 5]])

Question 17: Array Splitting Operations

In [11]:
# Q17.1: Split an array into 3 equal parts using np.split()
split_array=np.array([1,2,3,4,5,6,7,8,9])
splitted_array=np.split(split_array,3)
print(splitted_array)
for i, part in enumerate(splitted_array):
    print(f" part {i+1} : {part}")

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
 part 1 : [1 2 3]
 part 2 : [4 5 6]
 part 3 : [7 8 9]


In [12]:
# Q17.2: Split an array at specific indices using np.split()
split_arr=np.split(split_array,[4,5])
split_arr
for i, part in enumerate(split_arr):
    print(f"part{i+1}:{part}")

part1:[1 2 3 4]
part2:[5]
part3:[6 7 8 9]


In [22]:
# Q17.3: Split an array horizontally using np.hsplit()
split_horiz=np.hsplit(split_array,3)
print(split_horiz)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
hsplit_parts
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part{i+1}:\n{part}")

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Horizontal part1:
[[1]
 [4]]
Horizontal part2:
[[2]
 [5]]
Horizontal part3:
[[3]
 [6]]


In [23]:
# Q17.4: Split an array vertically using np.vsplit()
vsplit_parts=np.vsplit(arr_2d,2)
for i,part in enumerate(vsplit_parts):
    print(f"part{i+1}:\n{part}")

part1:
[[1 2 3]]
part2:
[[4 5 6]]


In [24]:
# Q17.5: Split an array into equal chunks using np.array_split()
array_split=np.array_split(arr_2d,2)
array_split
for i, parts in enumerate(array_split):
    print(f"parts{i+1}:\n{parts}")

parts1:
[[1 2 3]]
parts2:
[[4 5 6]]


#Question 18: Array Repetition and Tiling

In [25]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()
arr = np.array([1, 2, 3])
result = np.repeat(arr, 3)
print(result)

[1 1 1 2 2 2 3 3 3]


In [17]:
# Q18.2: Repeat an entire array 2 times using np.tile()
np.tile(arr,2)

array([1, 2, 3, 1, 2, 3])

In [28]:
# Q18.3: Repeat a 2D array using np.tile()
np.tile(arr_2d,(3,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [29]:
# Q18.4: Create a pattern using np.tile()
pattern = np.tile([1, 2, 3], (4, 2))
print(pattern)

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [30]:
# Q18.5: Repeat elements with different counts using np.repeat()
np.repeat([1,2,3],[4,5,6])

array([1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

Question 19: Array Comparison and Logical Operations

In [32]:
# print("\nQ19.1: Compare two arrays for equality using np.array_equal()")
arr1= np.array([1, 2, 3])
arr2= np.array([1, 2, 3])
arr3 = np.array([1, 2, 4])
print(f"A equals B: {np.array_equal(arr1, arr2)}")
print(f"A equals C: {np.array_equal(arr2, arr3)}")

A equals B: True
A equals C: False


In [36]:
# print("\nQ19.2: Check if arrays are close using np.allclose()")
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")

Arrays are close: True


In [35]:
# print("\nQ19.2: Check if arrays are close using np.allclose()")
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")

Arrays are close: True


In [37]:
# print("\nQ19.3: Apply logical AND operation between arrays")
logical_and = np.logical_and(arr1 >= 1, arr1 < 3)
print(f"Array: {arr1}")
print(f"Logical AND (1 < x < 3): {logical_and}")

Array: [1 2 3]
Logical AND (1 < x < 3): [ True  True False]


In [38]:
# print("\nQ19.4: Apply logical OR operation between arrays")
logical_or = np.logical_or(arr1 == 1, arr1 == 3)
print(f"Array: {arr1}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")

Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]


In [39]:
# print("\nQ19.5: Apply logical NOT operation to an array")
logical_not = np.logical_not(arr1 == 2)
print(f"Array: {arr1}")
print(f"Logical NOT (x != 2): {logical_not}")

Array: [1 2 3]
Logical NOT (x != 2): [ True False  True]


Question 20: Array Set Operations

In [40]:
# print("\nQ20.1: Find unique elements in an array using np.unique()")
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr_with_duplicates)
unique_elements

array([1, 2, 3, 4])

In [41]:
# print("\nQ20.2: Find the intersection of two arrays using np.intersect1d()")
arr1= np.array([1, 2, 3, 4])
arr2= np.array([3, 4, 5, 6])
array_intersection=np.intersect1d(arr1,arr2)
print(f" array intersection:{array_intersection}")

 array intersection:[3 4]


In [42]:
# print("\nQ20.3: Find the union of two arrays using np.union1d()")
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 5, 6])

In [43]:
# print("\nQ20.4: Find elements in first array but not in second using np.setdiff1d()")
np.setdiff1d(arr1,arr2)

array([1, 2])

In [44]:
# print("\nQ20.5: Find the symmetric difference between two arrays using np.setxor1d()")
np.setxor1d(arr1,arr2)

array([1, 2, 5, 6])