In [5]:
import numpy as np
import pandas as pd

In [6]:
# Create retail data: 10 rows × 5 columns
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock

retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

In [8]:
print(retail_data)
print(f"\nData Shape is:{retail_data.shape}")
print(f"\nData Type is :{retail_data.dtype}")

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Data Shape is:(10, 5)

Data Type is :float64


In [14]:
# print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# print("\nQ1.2: Create an array of 10 zeros using np.zeros()")
zeros_array=np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
# print("\nQ1.3: Create an array of 5 ones using np.ones()")
ones_array=np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [21]:
# print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")
array_values=np.arange(10)
print(array_values)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")
linespace_array=np.linspace(0,10,6) #linspace is basically used to divide the the given range evenly accprding to the didgit.
print(linespace_array)

[ 0.          3.33333333  6.66666667 10.        ]


# QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION


In [28]:
# print("\nQ2.1: What is the shape of the retail_data array?")
print(f"The shape of the retail data is: \n{retail_data.shape}")

The shape of the retail data is: 
(10, 5)


In [32]:
# print("\nQ2.2: What is the data type of the retail_data array?")
print(f"The data type of retail is :\n{retail_data.dtype}")

The data type of retail is :
float64


In [33]:
# print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")
print(f"The total size of the retail is:\n{retail_data.size}")

The total size of the retail is:
50


In [35]:
# print("\nQ2.4: What is the number of dimensions of the retail_data array?")
print(f"The dimenstion of retail is:\n{retail_data.ndim}")

The dimenstion of retail is:
2


In [36]:
# print("\nQ2.5: What is the memory size of the retail_data array in bytes?")
print(f"The memory size in bytes is:\n{retail_data.nbytes}")

The memory size in bytes is:
400


# QUESTION 3: INDEXING AND SLICING

In [37]:
# print("\nQ3.1: Extract the first row of retail_data")
first_row = retail_data[0]
print(first_row)

[1001.     29.99   45.      4.2    15.  ]


In [38]:
# print("\nQ3.2: Extract the last row of retail_data")
last_row=retail_data[-1]
print(last_row)

[1010.     59.99   34.      4.4    10.  ]


In [47]:
# print("\nQ3.3: Extract the Price column (column index 1)")
price_column=retail_data[:,1]
print(price_column)

[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]


In [41]:
# print("\nQ3.4: Extract the first 3 rows and first 2 columns")
rows_columns=retail_data[:3,:2]
print(rows_columns)

[[1001.     29.99]
 [1002.     49.99]
 [1003.     19.99]]


In [52]:
# print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
extract_rows = retail_data[2:6]
print(extract_rows)


[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


# QUESTION 4: MATHEMATICAL OPERATIONS

In [56]:
# print("\nQ4.1: Calculate the sum of all prices")
total_price=np.sum(retail_data[:,1])
print(f"The total sum of the Price is:\n${total_price}")


The total sum of the Price is:
$481.9


In [58]:
# print("\nQ4.2: Calculate the mean price")
mean_price=np.mean(retail_data[:,1])
print(f"The Mean of the price is:\n${mean_price}")

The Mean of the price is:
$48.19


In [61]:
# print("\nQ4.3: Calculate the standard deviation of prices")
std_deviation=np.std(retail_data[:,1])
print(f"The standard devaition of price is:\n${std_deviation:.2f}")

The standard devaition of price is:
$24.70


In [64]:
# print("\nQ4.4: Calculate the variance of prices")
var_price=np.var(retail_data[:,1])
print(f"The variance of the price is:\n${var_price}")

The variance of the price is:
$609.9599999999998


In [65]:
# print("\nQ4.5: Calculate the median price")
median_price=np.median(retail_data[:,1])
print(f"The median of the Price is:\n${median_price}")

The median of the Price is:
$44.99


# QUESTION 5: STATISTICAL FUNCTIONS

In [67]:
# print("\nQ5.1: Find the minimum and maximum prices")
min_price=np.min(retail_data[:,1])
max_price=np.max(retail_data[:,1])
print(f"The minimum price is: ${min_price}")
print(f"The maximum price is: ${max_price}")


The minimum price is: $15.99
The maximum price is: $89.99


In [9]:
# print("\nQ5.2: Find the minimum and maximum quantities sold")
min_sold=np.min(retail_data[:,2])
max_sold=np.max(retail_data[:,2])
print(f"The minimum sold quantity is:{min_sold}")
print(f"The maximum sold quantity is:{max_sold}")

The minimum sold quantity is:12.0
The maximum sold quantity is:95.0


In [10]:
# print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")
import numpy as np
percentiles= np.percentile(retail_data[:,1],[25,50,75])
print(f"25th percentile is :{percentiles[0]}")
print(f"50th percentile is :{percentiles[1]}")
print(f"75th percentile is :{percentiles[2]}")



25th percentile is :26.99
50th percentile is :44.99
75th percentile is :67.49


In [22]:
# print("\nQ5.4: Calculate the correlation between prices and quantities sold")
correlation=np.corrcoef(retail_data[:,1],retail_data[:,2])[0,1]
print(f"The correlation of price and quantity:{correlation:.4f}")

The correlation of price and quantity:-0.9291


In [23]:
# print("\nQ5.5: Calculate the covariance between prices and quantities sold")
covariance=np.cov(retail_data[:,1],retail_data[:,2])[0,1]
print(f"Covariance:{covariance:.4f}")


Covariance:-653.4444


# QUESTION 6: ARRAY RESHAPING AND MANIPULATION

In [26]:
# print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")
reshaped=retail_data.reshape(5,10)
print(reshaped)



[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]


In [28]:
# print("\nQ6.2: Flatten the retail_data to a 1D array")
flattend=retail_data.flatten()
print(flattend)

[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]


In [29]:
# print("\nQ6.3: Transpose the retail_data")
transpose=retail_data.T
print(transpose)

[[1001.   1002.   1003.   1004.   1005.   1006.   1007.   1008.   1009.
  1010.  ]
 [  29.99   49.99   19.99   89.99   15.99   69.99   39.99   79.99   25.99
    59.99]
 [  45.     32.     78.     12.     95.     28.     56.     18.     67.
    34.  ]
 [   4.2     4.5     3.8     4.7     4.      4.3     3.9     4.6     4.1
     4.4 ]
 [  15.      8.     22.      5.     18.     12.     20.      7.     16.
    10.  ]]


In [32]:
# print("\nQ6.4: Split the retail_data into 2 equal parts vertically")
vertical_split=np.vsplit(retail_data,2)
print(f"Fisrt vertical:{vertical_split[0]}")
print(f"Fisrt vertical:{vertical_split[1]}")

Fisrt vertical:[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]
Fisrt vertical:[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [ ]:
# print("\nQ6.5: Split the retail_data into 2 equal parts horizontally")
horizontal_split= np.hsplit(retail_data, 2)
print(f"fisrt hori:{horizontal_split[0]}")
print(f"fisrt hori:{horizontal_split[1]}")

# QUESTION 7: LOGICAL OPERATIONS AND FILTERING

In [ ]:
# print("\nQ7.1: Find products with price greater than $50")
high_price=retail_data[retail_data[:,1]>50]
print(high_price)

[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [ ]:
# print("\nQ7.2: Find products with customer rating greater than 4.0")

